export const LIVE_AUCTION = 'LIVE_AUCTION';
export const LIVE_AUCTION_VIEW = 'LIVE_AUCTION_VIEW';
export const UPCOMING_AUCTION = 'UPCOMING_AUCTION';
export const UPCOMING_AUCTION_VIEW = 'UPCOMING_AUCTION_VIEW';
export const TOTAL_BIDS = 'TOTAL_BIDS';
export const PARTICIPANTS_USER = 'PARTICIPANTS_USER';

