export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const UPDATE_CATEGORY_STATUS = 'UPDATE_CATEGORY_STATUS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
