export const FETCH_FEATURES = 'FETCH_FEATURES';
export const EDIT_FEATURE = 'EDIT_FEATURE';
export const UPDATE_FEATURE_STATUS  = 'UPDATE_FEATURE_STATUS';
export const DELETE_FEATURE  = 'DELETE_FEATURE';
export const FETCH_FEATURE_USERS  = 'FETCH_FEATURE_USERS';
